config/routes.rb
Timesheet::Application.routes.draw do

  resources :posts

  get "posts/index"
  
  get 'search' => 'posts#posts_date'
  
  match "posts(/date/:year/:month/:day)(/name/:name)" => "posts#posts_date"
  
  match "posts/totals/:year/:month" => "posts#totals"
  
  root :to => 'posts#index'
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :name, :worktype, :hours, :starttime, :endtime, :notes, :date
 
  ENGINEERNAMES =  [ "Andrew Kiernan",
                     "Andrew Loake",
                     "Andrew Mitchell",
                     "Andrew Twiselton",
                     "Andrius Stanaitis",
                     "Andrzej Jancy",
                     "Brian Murphy",
                     "Chris Murray",
                     "Claire Loughran",
                     "Claire Shields",
                     "Danique Burton",
                     "David Hunt",
                     "David Taylor",
                     "Felix Moshi",
                     "Gary Hiscutt",
                     "Ian Foote",
                     "Jack Hodge",
                     "Jamal Mohammed",
                     "Joel Pearson",
                     "John Williams",
                     "Josh Winter",
                     "Joshua Sharpless",
                     "Julie Quarton-Hill",
                     "Kamaldeen Abdulsalam",
                     "Ken Eastaff",
                     "Kibrul Chowdhury",
                     "Maciej Starkowski",
                     "Malcolm Wilson",
                     "Marco Stephenson",
                     "Mark Timms",
                     "Michael Haley",
                     "Michael Holland",
                     "Michael Mullen",
                     "Michael Thoulass",
                     "Michal Fijalkowski",
                     "Naranjan Atwal",
                     "Narinderjeet Matharu",
                     "Pat Gurney",
                     "Paul Barr",
                     "Peter Rowlson",
                     "Przemyslaw Kochanowski",
                     "Reece Winter",
                     "Richard Thurkle",
                     "Roger Marchant",
                     "Roxana Bugeac",
                     "Roy Mace",
                     "Ryan Monteith",
                     "Simon Mason",
                     "Simon Smith",
                     "Stephen Mukaro",
                     "Steve Welsh",
                     "Steven Middleton",
                     "Tim Barr",
                     "Tom Willingham",
                     "Tony Scinaldi",
                     "Tony White",
                     "Tracey Manners",
                     "Vernon Walton"
  ]

  NAMES = ENGINEERNAMES.map { |v| v.gsub(/\s+/, '') } + [ 'All' ]

  WORKTYPES =
  { 
    "Logistics" => 
      [
        "Admin",
        "Build",
        "Brokerage",
        "Driving",
        "Field",
        "Labour",
        "Project",
        "R&D",
        "QA",
        "Teardown",
        "Technical Support",
        "Training",
        "Warehouse"
      ],
    "Other" =>
      [
        "Other",
        "Break"
      ],
    "Repair" =>
      [
        "Repair Complete",
        "WIP",
        "BER"
      ]
  }  
  
  WORKTYPEEXAMPLES = {
    "Admin"             => "Paperwork / Stock Checks",
    "BER"               => "Non-RDT Job Beyond Economical Repair",
    "Brokerage"         => "Repair / Config for Brokerage",
    "Build"             => "Software Build",
    "Driving"           => "Trunk / Deliveries",
    "Field"             => "Working as a Driver / Field Engineer",
    "Labour"            => "Moving Desks / Cabling",
    "Other"             => "Detail in Notes",
    "Project"           => "Installs at Customer Site",
    "QA"                => "DOA / Quality Investigation",
    "R&D"               => "Research & Development",
    "Repair Complete"   => "Non-RDT Job Repaired",
    "Teardown"          => "Parts Harvesting",
    "Technical Support" => "Internal / Field",
    "Training"          => "Work-related Teaching / Learning",
    "WIP"               => "Non-RDT Job Work In Progress",
    "Warehouse"         => "Working in Warehouse",
    "Break"             => "Lunch / Tea Break"
  }
 
  validates :name, :presence => true
  validates :worktype, :presence => true, :format => /\A[^-]/
  validates :hours, :presence => true, :numericality => { :greater_than => 0, :less_than => 24 }
  validates :starttime, :presence => true, :format => /\A\d{1,2}\:[0-5]\d\z/
  validates :endtime, :presence => true, :format => /\A\d{1,2}\:[0-5]\d\z/
  validates :notes, :presence => true, :length => { :minimum => 4 }, :format => /\A[^=].+/
  
  before_validation :validate_values

  def self.filter( find_date, find_name )
    
    if find_name == 'All'
      where( :created_at => find_date.beginning_of_day..find_date.end_of_day ).order(:name)
    else
      where( :created_at => find_date.beginning_of_day..find_date.end_of_day, :name => find_name )
    end
  end
  
  def self.to_csv( options = {} )
    CSV.generate( options ) do |csv|
      csv << column_names
      all.each do |post|
        csv << post.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.worktype_hours_by_month( date )
    totals = Hash.new(0);Post.where( :created_at => date.beginning_of_month..date.end_of_month ).each {|p| totals[p.worktype]+=p.hours.to_f };totals
  end
  
  protected
  
  def validate_values
    allow_break
    strip_whitespace
    convert_hours
    strip_leading_zeros
  end
  
  def allow_break
    self.notes = 'Break' if notes.empty? && worktype == 'Break'
  end
  
  def strip_whitespace
    %w( hours starttime endtime ).each do |name|
      send( name + '=', send( name ).strip ) if send( name ).respond_to?( :strip )
    end
  end
  
  def convert_hours
    if hours_before_type_cast && hours_before_type_cast =~ /:/
      hrs, mins = hours_before_type_cast.scan( /(\d*):(\d*)/ ).first
      self.hours = BigDecimal( ( hrs.to_f + ( mins.to_f / 60.0 ) ), 4 )
    end
  end
  
  def strip_leading_zeros
    self.starttime, self.endtime = starttime.sub(/\A0+/,''), endtime.sub(/\A0+/,'')
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #http_basic_authenticate_with :name => "centrex", :password => "centrex", :except => [:index]

  # GET /posts
  # GET /posts.json
  def index
  
    session[ :viewdate ] = Date.today
  
    @posts = Post.where("created_at >= ?", Date.today).order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
      format.csv { send_data @posts.to_csv }
      format.xls
    end
    
  end

  def show
    redirect_to action: "index"
  end

  # GET /posts/yyyy/mm/dd/name/:name
  def posts_date

    if params[ :date ]
      session[ :viewdate ] = Date.parse params[ :date ]
    else
      session[ :viewdate ] = ( [ params[:year], params[:month], params[:day] ].all? ? Date.new( params[:year].to_i, params[:month].to_i, params[:day].to_i ) : Date.today )
    end
  
    session[ :name ] = if params[:name].nil?
      session[ :name ]
    elsif params[:name] == 'All'
      'All'
    elsif Post::NAMES.include?( params[:name] )
      Post::ENGINEERNAMES[ Post::NAMES.index( params[:name] ) ]
    elsif Post::ENGINEERNAMES.include?( params[:name] )
      params[ :name ]
    else
      'All'
    end

    @posts = Post.filter( session[ :viewdate ], session[ :name ] )
    
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @posts }
      format.csv { send_data @posts.to_csv }
      format.xls { render :index }
    end

  end
  
  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
  
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        session[ :name ] = @post.name
        session[ :viewdate ] = Date.today
        session[ :endtime ] = @post.endtime
        @posts = Post.filter( session[ :viewdate ], session[ :name ] )
        format.html { render :index }
        
        #format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        
        session[ :name ] = @post.name
        session[ :viewdate ] = @post.created_at.to_date
        session[ :endtime ] = @post.endtime
        @posts = Post.filter( session[ :viewdate ], session[ :name ] )
        format.html { render :index }
        
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
  
  def totals
     totals = Post.worktype_hours_by_month( Date.new( params[:year].to_i, params[:month].to_i, 1 ) ) 
     render :totals, :locals => { :totals => totals }
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<script language="javascript" type="text/javascript">

function CalculateHours(){
  var time1 = new Date();
  var time2 = new Date();
  time1.setHours( parseInt(post_starttime.value.split(':')[0]) );
  time1.setMinutes( parseInt(post_starttime.value.split(':')[1]) );
  time2.setHours( parseInt(post_endtime.value.split(':')[0]) );
  time2.setMinutes( parseInt(post_endtime.value.split(':')[1]) );
  var diff = new Date( time2 - time1 );
  post_hours.value = TimeString(diff)
}

  function TimeString(date){
    return date.getHours() + ':' + pad(date.getMinutes(), 2, 0)
  }

  function pad(n, width, z) {
    z = z || '0';
    n = n + '';
    return n.length >= width ? n : new Array(width - n.length + 1).join(z) + n
  }
  
</script>

<div style="float: right;
z-index: 10;
position: fixed;
right: 0;
top: 0;">

<p style="margin-right:5px;">All Worktypes refer to jobs not accounted for on ReDeTrack</p>
  <table border=1 cellpadding=1>
    <tr><th>WorkType<th>Example(s)
     <% Post::WORKTYPES.each do |group, values|
     values.each do |type|
     %>
        <tr><td><%= type %><td><%= Post::WORKTYPEEXAMPLES[ type ] %>
     <% end; end %>
</table>
</div>

<%= form_for(@post) do |post_form| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= post_form.label :name %><br />
    <%= post_form.select :name, options_for_select(Post::ENGINEERNAMES, @post.name || session[ :name ] ) %>
  </div>
  <div class="field">
    <%= post_form.label :worktype %><br />
    <%= post_form.select :worktype, grouped_options_for_select( Post::WORKTYPES, @post.worktype ) %>
  </div>
  <div class="field">
    <%= post_form.label :starttime %><br />  
    <%= post_form.text_field :starttime, :value => @post.starttime || session[ :endtime ] %>
  </div>
  <div class="field">
    <%= post_form.label :endtime %><br />  
    <%= post_form.text_field :endtime %>
  </div>
  <div class="field">
    <%= post_form.label :hours %><br />  
    <%= post_form.text_field :hours %>
    <button name="calculate" type="button" onclick="CalculateHours();">Calculate</button> 
  </div>  
  <div class="field">
    <label for="post_notes">Notes</label><br />
    <%= post_form.text_area :notes, :size => "50x5" %>
  </div>
  <div class="actions">
    <%= post_form.submit "Save" %>
  </div>
<% end %>

app/views/posts/_search.html.erb
<div style="float: right;
z-index: 10;
position: absolute;
right: 0;
top: 0;">

<%= form_tag search_path, :method => "get" do %>
  <table border=1>
  <tr>
  <th colspan="2">Filter Options:
  <tr>
  <td><%= label_tag 'name', "Name:" %>
  <td ><%= select_tag "name", options_for_select( ['All'] + Post::ENGINEERNAMES, ( session[ :name ] ? session[ :name ] : 'All' ) ) -%>
  <tr>
  <td><%= label_tag 'date', 'Date:' %>
  <td><%= select_tag 'date', options_for_select( (( Date.today-5 )..Date.today ), session[ :viewdate ] ), { 'style' => "width: 100%;" } %>
  <tr><td colspan="2" align="center"><%= submit_tag "Search" %>
  </table>
<%- end %>

</div>

app/views/posts/edit.html.erb
<h1>Editing Task</h1>

<%= link_to 'Back to Index', posts_path %>
<br />
<br />

<%= render 'form' %>

<%= link_to 'Back to Index', posts_path %>

app/views/posts/index.html.erb
<% if false %>
<meta http-equiv="refresh" content="300" />
<%= simple_format @post.to_yaml %>
<p>
  <b>created_at:</b>
  <%=h @post.created_at %>
</p>
<% end %>

<%= link_to 'Create Task', new_post_path %><br /><br />

<table border=1 cellpadding=2>
  <tr>
    <th>Name</th>
    <th>Worktype</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>Hours</th>
    <th>Notes</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  
<% @posts.each do |post| %>
  <tr class= "<%= post.name.gsub(' ','') %>">
    <td><%= post.name %></td>
    <td><%= post.worktype %></td>
    <td><%= post.starttime %></td>
    <td><%= post.endtime %></td>
    <td><%= post.hours %></td>
    <td><%= post.notes %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create Task', new_post_path %>

<br />
<br />

<%= render 'search' %>

<p>
  Download:
  <%= link_to "CSV", request.parameters.merge( { :format => :csv } ) %>| 
  <%= link_to "Excel", request.parameters.merge( { :format => :xls } ) %>
</p>

app/views/posts/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/Row/REC-html40">
  
  <ss:Styles>
  <Style ss:ID="s22"><NumberFormat ss:Format="dd/mm/yyyy"/></Style>
  </ss:Styles>
  
  <Worksheet ss:Name="Sheet1">

    <Table>
      <Row>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Worktype</Data></Cell>
        <Cell><Data ss:Type="String">Start Time</Data></Cell>
        <Cell><Data ss:Type="String">End Time</Data></Cell>
        <Cell><Data ss:Type="String">Hours</Data></Cell>
        <Cell><Data ss:Type="String">Notes</Data></Cell>
        <Cell><Data ss:Type="String">Date</Data></Cell>
      </Row>
      
    <% @posts.each do |post| %>
        <Row>
          <Cell><Data ss:Type="String"><%= post.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= post.worktype %></Data></Cell>
          <Cell><Data ss:Type="String"><%= post.starttime %></Data></Cell>
          <Cell><Data ss:Type="String"><%= post.endtime %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= post.hours %></Data></Cell>
          <Cell><Data ss:Type="String"><%= post.notes %></Data></Cell>
          <Cell ss:StyleID="s22"><Data ss:Type="DateTime"><%= post.created_at.to_date %></Data></Cell>
        </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/posts/new.html.erb
<h2>New Task</h2>

<%= link_to 'Back to Index', posts_path %>
<br />
<br />

<%= render 'form' %>

<%= link_to 'Back to Index', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
 
<p>
  <b>Worktype:</b>
  <%= @post.worktype %>
</p>
 
<p>
  <b>Hours:</b>
  <%= @post.hours %>
</p> 
 
<p>
  <b>Notes:</b>
  <%= @post.content %>
</p>
  
<%= link_to 'Edit Post', edit_post_path(@post) %> |
<%= link_to 'Back to Posts', posts_path %> |

app/views/posts/totals.html.erb
<table border=1 cellpadding=1>
  <tr><th>WorkType<th>Total Hours
   <% totals.each do |type, hours| %>
      <tr><td><%= type %><td><%= '%.2f' % hours %>
   <% end %>
</table>